import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class AvoidRetainAll {

    public static <T, R> List<T> retainAll(List<T> xs, List<R> elementsToRetains) {
        // mutable
        xs.retainAll(elementsToRetains);
        return xs;
    }

    public static <T> List<T> filter(List<T>xs, Predicate<T> p) {
        return xs.stream()
                .filter(p)
                .collect(Collectors.toList());
    }
}
